import type { GeneratedWorkerConfig } from './types.js';

function serialize(value: unknown): string {
  return JSON.stringify(value).replaceAll('<', '\\u003c');
}

export function generateServiceWorker(config: GeneratedWorkerConfig): string {
  const safeAppId = config.appId.replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-|-$/g, '') || 'app';
  const precacheName = `hf-${safeAppId}-precache-${config.buildId}`;
  const runtimePrefix = `hf-${safeAppId}-runtime-`;
  const configuredRuntimeRules = config.runtimeCaching ?? [];
  const ruleMatchers = configuredRuntimeRules.map((rule, index) =>
    rule.matchType === 'function'
      ? staticFunctionExpression(rule.matchFunctionSource, `runtime cache matcher ${index}`)
      : 'null');
  const privatePartitioners = configuredRuntimeRules.map((rule, index) =>
    rule.sensitiveData && rule.sensitiveData !== 'none'
      ? staticFunctionExpression(rule.sensitiveData.partitionKeySource, `private-cache partitioner ${index}`)
      : 'null');
  const runtimeCaching = configuredRuntimeRules.map((rule, index) => {
    const { matchFunctionSource: _matcher, sensitiveData, ...serializable } = rule;
    return {
      ...serializable,
      ruleIndex: index,
      ...(sensitiveData && sensitiveData !== 'none' ? {
        sensitiveData: {
          private: true,
          purgeOnLogout: sensitiveData.purgeOnLogout,
          threatReview: sensitiveData.threatReview,
        },
      } : sensitiveData ? { sensitiveData } : {}),
    };
  });
  const payload = {
    ...config,
    precacheName,
    runtimePrefix,
    runtimeCaching,
    navigationAllow: config.navigationAllow ?? [],
    navigationDeny: config.navigationDeny ?? ['/api/'],
    navigationTimeoutSeconds: config.navigationTimeoutSeconds ?? 3,
    cleanupOutdated: config.cleanupOutdated ?? true,
    legacyNamesToDelete: config.legacyNamesToDelete ?? [],
  };

  return `/* Generated by Homeframe ${config.buildId}. Do not edit. */
'use strict';
const HF = ${serialize(payload)};
const RULE_MATCHERS = [${ruleMatchers.join(',')}];
const PRIVATE_PARTITIONERS = [${privatePartitioners.join(',')}];
const PRECACHE_URLS = new Map(HF.precache.map((entry) => [new URL(entry.url, self.location.origin).href, entry]));

function postToClients(message) {
  return self.clients.matchAll({ type: 'window', includeUncontrolled: true })
    .then((clients) => Promise.all(clients.map((client) => client.postMessage(message))));
}

function matchesPattern(url, pattern, kind = 'prefix', flags = '') {
  try {
    if (kind === 'regex') return new RegExp(pattern, flags).test(url.href);
    if (kind === 'exact') return url.href === new URL(pattern, self.location.origin).href;
    return url.href.startsWith(new URL(pattern, self.location.origin).href);
  } catch {
    return false;
  }
}

function pathWithinScope(pathname) {
  const scope = new URL(HF.scope, self.location.origin).pathname;
  const prefix = scope.endsWith('/') ? scope : scope + '/';
  return pathname === scope || pathname.startsWith(prefix);
}

function looksLikeAssetPath(pathname) {
  const segment = pathname.slice(pathname.lastIndexOf('/') + 1);
  return /\\.[a-z0-9][a-z0-9._-]*$/i.test(segment);
}

function navigationAllowed(url) {
  if (url.origin !== self.location.origin) return false;
  if (!pathWithinScope(url.pathname) || looksLikeAssetPath(url.pathname)) return false;
  if (HF.navigationDeny.some((pattern) => matchesPattern(url, pattern))) return false;
  if (HF.navigationAllow.length === 0) return true;
  return HF.navigationAllow.some((pattern) => matchesPattern(url, pattern));
}

function notificationAllowlistMatch(pathname, configured) {
  try {
    const allowed = new URL(configured, self.location.origin).pathname;
    if (pathname === allowed) return true;
    const prefix = allowed.endsWith('/') ? allowed : allowed + '/';
    return pathname.startsWith(prefix);
  } catch {
    return false;
  }
}

async function validatedFetch(request) {
  const response = await fetch(request);
  if (!response || !response.ok || response.type === 'error') {
    throw new Error('Invalid response for ' + request.url + ': ' + (response?.status ?? 'none'));
  }
  return response;
}

async function sha256(buffer, salt) {
  const saltBytes = new TextEncoder().encode(salt || '');
  const body = new Uint8Array(buffer);
  const combined = new Uint8Array(body.byteLength + saltBytes.byteLength);
  combined.set(body, 0);
  combined.set(saltBytes, body.byteLength);
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', combined));
  return [...digest].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

async function verifiedPrecacheResponse(entry) {
  const request = new Request(entry.url, { cache: 'reload', credentials: 'same-origin' });
  const response = await validatedFetch(request);
  if (!/^[a-f0-9]{64}$/i.test(entry.revision)) return { request, response };
  const assertedRevision = response.headers.get('x-homeframe-revision');
  if (assertedRevision) {
    if (assertedRevision.toLowerCase() !== entry.revision.toLowerCase()) {
      throw new Error('Revision attestation mismatch for ' + entry.url + ': expected ' + entry.revision + ', received ' + assertedRevision);
    }
    return { request, response };
  }
  const body = await response.arrayBuffer();
  const actual = await sha256(body, HF.revisionSalt);
  if (actual !== entry.revision.toLowerCase()) {
    throw new Error('Revision mismatch for ' + entry.url + ': expected ' + entry.revision + ', received ' + actual);
  }
  return {
    request,
    response: new Response(body, {
      status: response.status,
      statusText: response.statusText,
      headers: response.headers,
    }),
  };
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(HF.precacheName);
      await Promise.all(HF.precache.map(async (entry) => {
        const { request, response } = await verifiedPrecacheResponse(entry);
        await cache.put(request, response);
      }));
      await postToClients({ type: 'HF_UPDATE_READY', buildId: HF.buildId });
    } catch (error) {
      await caches.delete(HF.precacheName);
      throw error;
    }
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    if (HF.cleanupOutdated) {
      const names = await caches.keys();
      const ownedPrecachePrefix = 'hf-' + ${serialize(safeAppId)} + '-precache-';
      await Promise.all(names.map((name) => {
        const obsolete = name.startsWith(ownedPrecachePrefix) && name !== HF.precacheName;
        const explicitlyLegacy = HF.legacyNamesToDelete.includes(name);
        return obsolete || explicitlyLegacy
          ? Promise.all([caches.delete(name), purgeMetaCache(name).catch(() => undefined)])
          : Promise.resolve(false);
      }));
    }
    await self.clients.claim();
    await postToClients({ type: 'HF_ACTIVATED', buildId: HF.buildId });
  })());
});

function timeoutPromise(seconds) {
  return new Promise((_, reject) => setTimeout(() => reject(new Error('Network timeout')), seconds * 1000));
}

async function handleNavigation(request) {
  try {
    return await Promise.race([
      validatedFetch(request),
      timeoutPromise(HF.navigationTimeoutSeconds),
    ]);
  } catch {
    const cache = await caches.open(HF.precacheName);
    return await cache.match(HF.documentFallback, { ignoreSearch: true })
      || new Response('Offline', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}

function ruleFor(request) {
  const url = new URL(request.url);
  return HF.runtimeCaching.find((rule) => {
    if (rule.matchType === 'function') {
      try { return Boolean(RULE_MATCHERS[rule.ruleIndex]?.(request, url)); }
      catch { return false; }
    }
    return matchesPattern(url, rule.match, rule.matchType, rule.matchFlags);
  });
}

function responseAllowed(response, rule) {
  const statuses = rule.statuses ?? [200];
  const types = rule.responseTypes ?? ['basic', 'cors', 'default'];
  return statuses.includes(response.status) && types.includes(response.type);
}

function openMetaDb() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('homeframe-cache-meta', 1);
    request.onupgradeneeded = () => request.result.createObjectStore('entries', { keyPath: 'key' });
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function withMetaStore(mode, action) {
  const db = await openMetaDb();
  try {
    const transaction = db.transaction('entries', mode);
    const store = transaction.objectStore('entries');
    const result = await action(store);
    await new Promise((resolve, reject) => {
      transaction.oncomplete = resolve;
      transaction.onerror = () => reject(transaction.error);
      transaction.onabort = () => reject(transaction.error);
    });
    return result;
  } finally {
    db.close();
  }
}

function requestValue(request) {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function touchMeta(cacheName, url, updated) {
  const now = Date.now();
  const previous = await getMeta(cacheName, url);
  await withMetaStore('readwrite', (store) => requestValue(store.put({
    key: cacheName + '|' + url,
    cacheName,
    url,
    updatedAt: updated ? now : previous?.updatedAt ?? now,
    lastAccessAt: now,
  })));
}

async function getMeta(cacheName, url) {
  return withMetaStore('readonly', (store) => requestValue(store.get(cacheName + '|' + url)));
}

async function deleteMeta(cacheName, url) {
  return withMetaStore('readwrite', (store) => requestValue(store.delete(cacheName + '|' + url)));
}

async function purgeMetaCache(cacheName) {
  return withMetaStore('readwrite', async (store) => {
    const keys = await requestValue(store.getAllKeys());
    await Promise.all(keys
      .filter((key) => typeof key === 'string' && key.startsWith(cacheName + '|'))
      .map((key) => requestValue(store.delete(key))));
  });
}

async function trimRuntimeCache(rule) {
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const entries = await Promise.all(keys.map(async (request) => ({
    request,
    meta: await getMeta(cacheName, request.url),
  })));
  const now = Date.now();
  const expired = entries.filter(({ meta }) => !meta || now - meta.updatedAt > rule.maxAgeSeconds * 1000);
  const remaining = entries.filter(({ meta }) => meta && now - meta.updatedAt <= rule.maxAgeSeconds * 1000)
    .sort((a, b) => (a.meta.lastAccessAt ?? 0) - (b.meta.lastAccessAt ?? 0));
  const excess = remaining.slice(0, Math.max(0, remaining.length - rule.maxEntries));
  await Promise.all([...expired, ...excess].map(async ({ request }) => {
    await cache.delete(request);
    await deleteMeta(cacheName, request.url).catch(() => undefined);
  }));
}

async function evictOldestRuntimeEntries(rule) {
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const entries = await Promise.all(keys.map(async (request) => ({
    request,
    meta: await getMeta(cacheName, request.url).catch(() => null),
  })));
  entries.sort((a, b) => (a.meta?.lastAccessAt ?? 0) - (b.meta?.lastAccessAt ?? 0));
  const count = Math.max(1, Math.ceil(entries.length * 0.2));
  await Promise.all(entries.slice(0, count).map(async ({ request }) => {
    await cache.delete(request);
    await deleteMeta(cacheName, request.url).catch(() => undefined);
  }));
}

function isQuotaError(error) {
  return error?.name === 'QuotaExceededError'
    || /quota|storage/i.test(String(error?.message || error || ''));
}

async function cacheKey(request, rule) {
  const headers = new Headers(request.headers);
  if (rule.rangeRequests) headers.delete('range');
  let url = request.url;
  if (rule.sensitiveData?.private) {
    try {
      const value = await PRIVATE_PARTITIONERS[rule.ruleIndex]?.(request);
      if (typeof value !== 'string' || !value || value.length > 512) return null;
      const digest = await sha256(new TextEncoder().encode(value), 'homeframe-private-partition');
      const partitioned = new URL(request.url);
      partitioned.searchParams.set('__hf_partition', digest);
      url = partitioned.href;
    } catch {
      // Missing identity is network-only. Never fall back to an unpartitioned
      // key for data explicitly classified as private.
      return null;
    }
  }
  if (url === request.url && headers.get('range') === request.headers.get('range')) return request;
  return new Request(url, { headers, credentials: request.credentials });
}

async function rangedResponse(response, rangeHeader) {
  const match = /^bytes=(\\d*)-(\\d*)$/.exec(rangeHeader.trim());
  const buffer = await response.arrayBuffer();
  const total = buffer.byteLength;
  const headers = new Headers(response.headers);
  headers.delete('content-encoding');
  headers.set('accept-ranges', 'bytes');
  if (!match || (!match[1] && !match[2])) {
    headers.set('content-range', 'bytes */' + total);
    headers.set('content-length', '0');
    return new Response(null, { status: 416, headers });
  }

  let start;
  let end;
  if (!match[1]) {
    const suffix = Number(match[2]);
    if (!Number.isInteger(suffix) || suffix <= 0) {
      headers.set('content-range', 'bytes */' + total);
      headers.set('content-length', '0');
      return new Response(null, { status: 416, headers });
    }
    start = Math.max(0, total - suffix);
    end = total - 1;
  } else {
    start = Number(match[1]);
    end = match[2] ? Math.min(Number(match[2]), total - 1) : total - 1;
  }
  if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || start >= total || end < start) {
    headers.set('content-range', 'bytes */' + total);
    headers.set('content-length', '0');
    return new Response(null, { status: 416, headers });
  }

  const body = buffer.slice(start, end + 1);
  headers.set('content-range', 'bytes ' + start + '-' + end + '/' + total);
  headers.set('content-length', String(body.byteLength));
  return new Response(body, { status: 206, statusText: 'Partial Content', headers });
}

async function cacheMatch(request, rule) {
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const key = await cacheKey(request, rule);
  if (!key) return null;
  const response = await cache.match(key);
  if (response) await touchMeta(cacheName, key.url, false);
  const range = rule.rangeRequests ? request.headers.get('range') : null;
  return response && range ? rangedResponse(response, range) : response;
}

async function cachePut(request, response, rule) {
  if (!responseAllowed(response, rule)) return response;
  // A 206 response is only a fragment and must never replace the full cached
  // object. Servers that ignore Range and return 200 can still seed the cache.
  if (rule.rangeRequests && response.status === 206) return response;
  const cacheCandidate = await boundedCacheResponse(response, rule.maxResponseBytes ?? 32 * 1024 * 1024);
  if (!cacheCandidate) return response;
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const key = await cacheKey(request, rule);
  if (!key) return response;
  try {
    await cache.put(key, cacheCandidate.clone());
  } catch (error) {
    if (!isQuotaError(error)) return response;
    await evictOldestRuntimeEntries(rule).catch(() => undefined);
    try {
      await cache.put(key, cacheCandidate.clone());
    } catch {
      return response;
    }
  }
  await touchMeta(cacheName, key.url, true).catch(() => undefined);
  await trimRuntimeCache(rule).catch(() => undefined);
  return response;
}

async function boundedCacheResponse(response, maximumBytes) {
  if (response.type === 'opaque') return null;
  const declared = Number(response.headers.get('content-length'));
  if (Number.isFinite(declared) && declared > maximumBytes) return null;
  const clone = response.clone();
  if (!clone.body) {
    const buffer = await clone.arrayBuffer();
    if (buffer.byteLength > maximumBytes) return null;
    return rebuildResponse(response, new Uint8Array(buffer));
  }
  const reader = clone.body.getReader();
  const chunks = [];
  let total = 0;
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > maximumBytes) {
      await reader.cancel('Homeframe runtime response exceeds maxResponseBytes.').catch(() => undefined);
      return null;
    }
    chunks.push(value);
  }
  const body = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    body.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return rebuildResponse(response, body);
}

function rebuildResponse(response, body) {
  const headers = new Headers(response.headers);
  headers.delete('content-encoding');
  headers.set('content-length', String(body.byteLength));
  return new Response(body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

async function handleRuntime(request, rule, event) {
  if (rule.strategy === 'network-only') return fetch(request);
  if (rule.strategy === 'cache-only') {
    return await cacheMatch(request, rule) || new Response('Not cached', { status: 504 });
  }
  if (rule.strategy === 'cache-first') {
    return await cacheMatch(request, rule) || cachePut(request, await fetch(request), rule);
  }
  if (rule.strategy === 'network-first') {
    try {
      const response = await Promise.race([
        fetch(request),
        timeoutPromise(rule.networkTimeoutSeconds ?? 3),
      ]);
      return await cachePut(request, response, rule);
    } catch {
      return await cacheMatch(request, rule) || new Response('Offline', { status: 503 });
    }
  }
  const cached = await cacheMatch(request, rule);
  const revalidate = fetch(request).then((response) => cachePut(request, response, rule));
  if (cached) {
    event.waitUntil(revalidate.catch(() => undefined));
    return cached;
  }
  return revalidate;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (request.mode === 'navigate' && navigationAllowed(url)) {
    event.respondWith(handleNavigation(request));
    return;
  }
  if (PRECACHE_URLS.has(url.href)) {
    event.respondWith(caches.open(HF.precacheName).then(async (cache) =>
      // Precache entries are exact-URL and content-hash verified during
      // installation. Ignore response Vary headers here so common static-host
      // Vary: Origin policies cannot make present shell assets miss offline.
      await cache.match(request, { ignoreSearch: false, ignoreVary: true }) || fetch(request)));
    return;
  }
  const rule = ruleFor(request);
  if (rule) event.respondWith(handleRuntime(request, rule, event));
});

self.addEventListener('message', (event) => {
  const message = event.data || {};
  if (message.type === 'HF_SKIP_WAITING') {
    event.waitUntil(self.skipWaiting());
  } else if (message.type === 'HF_GET_VERSION') {
    event.ports[0]?.postMessage({ type: 'HF_VERSION', buildId: HF.buildId });
  } else if (message.type === 'HF_PURGE_RUNTIME' && typeof message.cacheName === 'string') {
    const allowed = HF.runtimeCaching.some((rule) => rule.cacheName === message.cacheName);
    if (allowed) {
      const cacheName = HF.runtimePrefix + message.cacheName;
      event.waitUntil(Promise.all([
        caches.delete(cacheName),
        purgeMetaCache(cacheName).catch(() => undefined),
      ]).then(() => event.ports[0]?.postMessage({ ok: true })));
    } else {
      event.ports[0]?.postMessage({ ok: false, error: 'Unknown app-owned runtime cache.' });
    }
  } else if (message.type === 'HF_PURGE_PRIVATE') {
    const names = HF.runtimeCaching
      .filter((rule) => rule.sensitiveData?.private && rule.sensitiveData.purgeOnLogout)
      .map((rule) => HF.runtimePrefix + rule.cacheName);
    event.waitUntil(Promise.all(names.flatMap((cacheName) => [
      caches.delete(cacheName),
      purgeMetaCache(cacheName).catch(() => undefined),
    ])).then(() => event.ports[0]?.postMessage({ ok: true, purged: names.length })));
  } else if (message.type === 'HF_SET_BADGE') {
    if (message.count > 0 && 'setAppBadge' in self.navigator) {
      event.waitUntil(self.navigator.setAppBadge(message.count));
    } else if ('clearAppBadge' in self.navigator) {
      event.waitUntil(self.navigator.clearAppBadge());
    } else if ('setAppBadge' in self.navigator) {
      event.waitUntil(self.navigator.setAppBadge(0));
    }
  }
});

function notificationRouteAllowed(route) {
  try {
    if (typeof route !== 'string' || route.length > 2048) return false;
    const url = new URL(route || HF.documentFallback, self.location.origin);
    if (url.origin !== self.location.origin || !pathWithinScope(url.pathname)) return false;
    const allowlist = HF.notifications?.routeAllowlist ?? [];
    return allowlist.length === 0 || allowlist.some((prefix) => notificationAllowlistMatch(url.pathname, prefix));
  } catch {
    return false;
  }
}

function notificationActions(value) {
  if (!Array.isArray(value)) return undefined;
  const actions = value.slice(0, 2).flatMap((item) => {
    if (!item || typeof item !== 'object') return [];
    const action = typeof item.action === 'string' ? item.action.slice(0, 32) : '';
    const title = typeof item.title === 'string' ? item.title.slice(0, 64) : '';
    if (!action || !title) return [];
    return [{ action, title, icon: notificationAsset(item.icon) }];
  });
  return actions.length ? actions : undefined;
}

function notificationText(value, fallback, maximum) {
  return (typeof value === 'string' ? value : fallback || '').slice(0, maximum);
}

function notificationAsset(value, fallback) {
  try {
    const candidate = typeof value === 'string' && value.length <= 2048 ? value : fallback;
    if (typeof candidate !== 'string' || candidate.length > 2048) return undefined;
    const url = new URL(candidate, self.location.origin);
    return url.origin === self.location.origin && pathWithinScope(url.pathname) ? url.href : undefined;
  } catch {
    return undefined;
  }
}

function applicationServerKeyBytes(value) {
  if (typeof value !== 'string' || !value) return undefined;
  try {
    const padding = '='.repeat((4 - value.length % 4) % 4);
    const raw = atob((value + padding).replaceAll('-', '+').replaceAll('_', '/'));
    return Uint8Array.from(raw, (character) => character.charCodeAt(0));
  } catch {
    return undefined;
  }
}

async function synchronizeRotatedSubscription(oldEndpoint, subscription) {
  const endpoint = HF.notifications?.subscriptionTransport;
  if (!endpoint) return;
  const url = new URL(endpoint, self.location.origin);
  if (url.origin !== self.location.origin) throw new Error('Push subscription transport must be same-origin.');
  if (oldEndpoint) {
    const removed = await fetch(url, {
      method: 'DELETE',
      credentials: 'same-origin',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ endpoint: oldEndpoint }),
    });
    if (!removed.ok && removed.status !== 404) throw new Error('Push subscription rotation delete failed: ' + removed.status);
  }
  if (subscription) {
    const updated = await fetch(url, {
      method: 'PUT',
      credentials: 'same-origin',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(subscription.toJSON()),
    });
    if (!updated.ok) throw new Error('Push subscription rotation update failed: ' + updated.status);
  }
}

if (HF.notifications) {
  self.addEventListener('push', (event) => {
    event.waitUntil((async () => {
      let data = {};
      try {
        const raw = event.data?.text() ?? '';
        const maximum = HF.notifications.maximumPayloadBytes ?? 16384;
        if (new TextEncoder().encode(raw).byteLength > maximum) throw new Error('Push payload exceeds configured limit.');
        data = raw ? JSON.parse(raw) : {};
        if (!data || typeof data !== 'object' || Array.isArray(data)) data = {};
        if (data.version !== undefined && data.version !== 1) data = {};
      } catch { data = {}; }
      const title = notificationText(data.title, HF.notifications.defaultTitle || 'Notification', 120);
      const body = notificationText(data.body, HF.notifications.defaultBody || '', 500);
      const route = notificationRouteAllowed(data.route) ? data.route : HF.documentFallback;
      const tag = typeof data.tag === 'string' ? data.tag.slice(0, 120) : undefined;
      const options = {
        body,
        icon: notificationAsset(data.icon, HF.notifications.defaultIcon),
        badge: notificationAsset(data.badge, HF.notifications.defaultBadge),
        image: notificationAsset(data.image),
        actions: notificationActions(data.actions),
        tag,
        renotify: Boolean(data.renotify && tag),
        silent: Boolean(data.silent),
        requireInteraction: Boolean(data.requireInteraction),
        data: { route, payloadVersion: Number(data.version || 1) },
      };
      if (Number.isFinite(data.badgeCount)) {
        const count = Math.max(0, data.badgeCount);
        if (count > 0 && 'setAppBadge' in self.navigator) await self.navigator.setAppBadge(count);
        else if ('clearAppBadge' in self.navigator) await self.navigator.clearAppBadge();
        else if ('setAppBadge' in self.navigator) await self.navigator.setAppBadge(0);
      }
      await self.registration.showNotification(title, options);
    })());
  });

  self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil((async () => {
      const route = notificationRouteAllowed(event.notification.data?.route)
        ? event.notification.data.route
        : HF.documentFallback;
      const target = new URL(route, self.location.origin).href;
      const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      const sameOrigin = clients.filter((item) => new URL(item.url).origin === self.location.origin);
      const client = sameOrigin.find((item) => item.visibilityState === 'visible') || sameOrigin[0];
      if (client) {
        await client.focus();
        client.postMessage({ type: 'HF_NOTIFICATION_ROUTE', route });
      } else {
        await self.clients.openWindow(target);
      }
    })());
  });

  self.addEventListener('notificationclose', (event) => {
    event.waitUntil(postToClients({
      type: 'HF_NOTIFICATION_CLOSE',
      tag: event.notification.tag || null,
    }));
  });

  self.addEventListener('pushsubscriptionchange', (event) => {
    event.waitUntil((async () => {
      let subscription = event.newSubscription || null;
      if (!subscription && (event.oldSubscription?.options || HF.notifications.applicationServerKey)) {
        try {
          subscription = await self.registration.pushManager.subscribe(event.oldSubscription?.options || {
            userVisibleOnly: true,
            applicationServerKey: applicationServerKeyBytes(HF.notifications.applicationServerKey),
          });
        } catch {
          subscription = null;
        }
      }
      await synchronizeRotatedSubscription(event.oldSubscription?.endpoint || null, subscription);
      await postToClients({
        type: 'HF_PUSH_SUBSCRIPTION_CHANGE',
        oldEndpoint: event.oldSubscription?.endpoint || null,
        subscription: subscription?.toJSON?.() || null,
      });
    })());
  });
}
`;
}

function staticFunctionExpression(source: string | undefined, label: string): string {
  const candidate = source?.trim() ?? '';
  if (!candidate || candidate.includes('[native code]') || candidate.length > 16_384) {
    throw new Error(`Invalid ${label}: expected a self-contained function smaller than 16 KiB.`);
  }
  try {
    void new Function(`return (${candidate});`);
  } catch (reason) {
    throw new Error(`Invalid ${label}: ${reason instanceof Error ? reason.message : String(reason)}`);
  }
  return `(${candidate})`;
}
