import type { GeneratedWorkerConfig } from './types.js';

function serialize(value: unknown): string {
  return JSON.stringify(value).replaceAll('<', '\\u003c');
}

export function generateServiceWorker(config: GeneratedWorkerConfig): string {
  const safeAppId = config.appId.replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-|-$/g, '') || 'app';
  const precacheName = `hf-${safeAppId}-precache-${config.buildId}`;
  const runtimePrefix = `hf-${safeAppId}-runtime-`;
  const payload = {
    ...config,
    precacheName,
    runtimePrefix,
    runtimeCaching: config.runtimeCaching ?? [],
    navigationAllow: config.navigationAllow ?? [],
    navigationDeny: config.navigationDeny ?? ['/api/', '/__homeframe/recovery'],
    navigationTimeoutSeconds: config.navigationTimeoutSeconds ?? 3,
    cleanupOutdated: config.cleanupOutdated ?? true,
    legacyNamesToDelete: config.legacyNamesToDelete ?? [],
  };

  return `/* Generated by Homeframe ${config.buildId}. Do not edit. */
'use strict';
const HF = ${serialize(payload)};
const PRECACHE_URLS = new Map(HF.precache.map((entry) => [new URL(entry.url, self.location.origin).href, entry]));

function postToClients(message) {
  return self.clients.matchAll({ type: 'window', includeUncontrolled: true })
    .then((clients) => Promise.all(clients.map((client) => client.postMessage(message))));
}

function matchesPattern(url, pattern, kind = 'prefix') {
  try {
    if (kind === 'regex') return new RegExp(pattern).test(url.href);
    if (kind === 'exact') return url.href === new URL(pattern, self.location.origin).href;
    return url.href.startsWith(new URL(pattern, self.location.origin).href);
  } catch {
    return false;
  }
}

function pathWithinScope(pathname) {
  const scope = new URL(HF.scope, self.location.origin).pathname;
  const prefix = scope.endsWith('/') ? scope : scope + '/';
  return pathname === scope || pathname.startsWith(prefix);
}

function looksLikeAssetPath(pathname) {
  const segment = pathname.slice(pathname.lastIndexOf('/') + 1);
  return /\\.[a-z0-9][a-z0-9._-]*$/i.test(segment);
}

function navigationAllowed(url) {
  if (url.origin !== self.location.origin) return false;
  if (!pathWithinScope(url.pathname) || looksLikeAssetPath(url.pathname)) return false;
  if (HF.navigationDeny.some((pattern) => matchesPattern(url, pattern))) return false;
  if (HF.navigationAllow.length === 0) return true;
  return HF.navigationAllow.some((pattern) => matchesPattern(url, pattern));
}

async function validatedFetch(request) {
  const response = await fetch(request);
  if (!response || !response.ok || response.type === 'error') {
    throw new Error('Invalid response for ' + request.url + ': ' + (response?.status ?? 'none'));
  }
  return response;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(HF.precacheName);
      await Promise.all(HF.precache.map(async (entry) => {
        const request = new Request(entry.url, { cache: 'reload', credentials: 'same-origin' });
        const response = await validatedFetch(request);
        await cache.put(request, response);
      }));
      await postToClients({ type: 'HF_UPDATE_READY', buildId: HF.buildId });
    } catch (error) {
      await caches.delete(HF.precacheName);
      throw error;
    }
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    if (HF.cleanupOutdated) {
      const names = await caches.keys();
      const ownedPrecachePrefix = 'hf-' + ${serialize(safeAppId)} + '-precache-';
      await Promise.all(names.map((name) => {
        const obsolete = name.startsWith(ownedPrecachePrefix) && name !== HF.precacheName;
        const explicitlyLegacy = HF.legacyNamesToDelete.includes(name);
        return obsolete || explicitlyLegacy ? caches.delete(name) : Promise.resolve(false);
      }));
    }
    await self.clients.claim();
    await postToClients({ type: 'HF_ACTIVATED', buildId: HF.buildId });
  })());
});

function timeoutPromise(seconds) {
  return new Promise((_, reject) => setTimeout(() => reject(new Error('Network timeout')), seconds * 1000));
}

async function handleNavigation(request) {
  try {
    return await Promise.race([
      validatedFetch(request),
      timeoutPromise(HF.navigationTimeoutSeconds),
    ]);
  } catch {
    const cache = await caches.open(HF.precacheName);
    return await cache.match(HF.documentFallback, { ignoreSearch: true })
      || new Response('Offline', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}

function ruleFor(request) {
  const url = new URL(request.url);
  return HF.runtimeCaching.find((rule) => matchesPattern(url, rule.match, rule.matchType));
}

function responseAllowed(response, rule) {
  const statuses = rule.statuses ?? [200];
  const types = rule.responseTypes ?? ['basic', 'cors', 'default'];
  return statuses.includes(response.status) && types.includes(response.type);
}

function openMetaDb() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('homeframe-cache-meta', 1);
    request.onupgradeneeded = () => request.result.createObjectStore('entries', { keyPath: 'key' });
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function withMetaStore(mode, action) {
  const db = await openMetaDb();
  try {
    const transaction = db.transaction('entries', mode);
    const store = transaction.objectStore('entries');
    const result = await action(store);
    await new Promise((resolve, reject) => {
      transaction.oncomplete = resolve;
      transaction.onerror = () => reject(transaction.error);
      transaction.onabort = () => reject(transaction.error);
    });
    return result;
  } finally {
    db.close();
  }
}

function requestValue(request) {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function touchMeta(cacheName, url, updated) {
  const now = Date.now();
  const previous = await getMeta(cacheName, url);
  await withMetaStore('readwrite', (store) => requestValue(store.put({
    key: cacheName + '|' + url,
    cacheName,
    url,
    updatedAt: updated ? now : previous?.updatedAt ?? now,
    lastAccessAt: now,
  })));
}

async function getMeta(cacheName, url) {
  return withMetaStore('readonly', (store) => requestValue(store.get(cacheName + '|' + url)));
}

async function trimRuntimeCache(rule) {
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const entries = await Promise.all(keys.map(async (request) => ({
    request,
    meta: await getMeta(cacheName, request.url),
  })));
  const now = Date.now();
  const expired = entries.filter(({ meta }) => !meta || now - meta.updatedAt > rule.maxAgeSeconds * 1000);
  const remaining = entries.filter(({ meta }) => meta && now - meta.updatedAt <= rule.maxAgeSeconds * 1000)
    .sort((a, b) => (a.meta.lastAccessAt ?? 0) - (b.meta.lastAccessAt ?? 0));
  const excess = remaining.slice(0, Math.max(0, remaining.length - rule.maxEntries));
  await Promise.all([...expired, ...excess].map(({ request }) => cache.delete(request)));
}

async function evictOldestRuntimeEntries(rule) {
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const entries = await Promise.all(keys.map(async (request) => ({
    request,
    meta: await getMeta(cacheName, request.url).catch(() => null),
  })));
  entries.sort((a, b) => (a.meta?.lastAccessAt ?? 0) - (b.meta?.lastAccessAt ?? 0));
  const count = Math.max(1, Math.ceil(entries.length * 0.2));
  await Promise.all(entries.slice(0, count).map(({ request }) => cache.delete(request)));
}

function isQuotaError(error) {
  return error?.name === 'QuotaExceededError'
    || /quota|storage/i.test(String(error?.message || error || ''));
}

function cacheKey(request, rule) {
  if (!rule.rangeRequests || !request.headers.has('range')) return request;
  const headers = new Headers(request.headers);
  headers.delete('range');
  return new Request(request, { headers });
}

async function rangedResponse(response, rangeHeader) {
  const match = /^bytes=(\\d*)-(\\d*)$/.exec(rangeHeader.trim());
  const buffer = await response.arrayBuffer();
  const total = buffer.byteLength;
  const headers = new Headers(response.headers);
  headers.delete('content-encoding');
  headers.set('accept-ranges', 'bytes');
  if (!match || (!match[1] && !match[2])) {
    headers.set('content-range', 'bytes */' + total);
    headers.set('content-length', '0');
    return new Response(null, { status: 416, headers });
  }

  let start;
  let end;
  if (!match[1]) {
    const suffix = Number(match[2]);
    if (!Number.isInteger(suffix) || suffix <= 0) {
      headers.set('content-range', 'bytes */' + total);
      headers.set('content-length', '0');
      return new Response(null, { status: 416, headers });
    }
    start = Math.max(0, total - suffix);
    end = total - 1;
  } else {
    start = Number(match[1]);
    end = match[2] ? Math.min(Number(match[2]), total - 1) : total - 1;
  }
  if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || start >= total || end < start) {
    headers.set('content-range', 'bytes */' + total);
    headers.set('content-length', '0');
    return new Response(null, { status: 416, headers });
  }

  const body = buffer.slice(start, end + 1);
  headers.set('content-range', 'bytes ' + start + '-' + end + '/' + total);
  headers.set('content-length', String(body.byteLength));
  return new Response(body, { status: 206, statusText: 'Partial Content', headers });
}

async function cacheMatch(request, rule) {
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const key = cacheKey(request, rule);
  const response = await cache.match(key);
  if (response) await touchMeta(cacheName, request.url, false);
  const range = rule.rangeRequests ? request.headers.get('range') : null;
  return response && range ? rangedResponse(response, range) : response;
}

async function cachePut(request, response, rule) {
  if (!responseAllowed(response, rule)) return response;
  // A 206 response is only a fragment and must never replace the full cached
  // object. Servers that ignore Range and return 200 can still seed the cache.
  if (rule.rangeRequests && response.status === 206) return response;
  const cacheName = HF.runtimePrefix + rule.cacheName;
  const cache = await caches.open(cacheName);
  const key = cacheKey(request, rule);
  try {
    await cache.put(key, response.clone());
  } catch (error) {
    if (!isQuotaError(error)) return response;
    await evictOldestRuntimeEntries(rule).catch(() => undefined);
    try {
      await cache.put(key, response.clone());
    } catch {
      return response;
    }
  }
  await touchMeta(cacheName, request.url, true).catch(() => undefined);
  await trimRuntimeCache(rule).catch(() => undefined);
  return response;
}

async function handleRuntime(request, rule, event) {
  if (rule.strategy === 'network-only') return fetch(request);
  if (rule.strategy === 'cache-only') {
    return await cacheMatch(request, rule) || new Response('Not cached', { status: 504 });
  }
  if (rule.strategy === 'cache-first') {
    return await cacheMatch(request, rule) || cachePut(request, await fetch(request), rule);
  }
  if (rule.strategy === 'network-first') {
    try {
      const response = await Promise.race([
        fetch(request),
        timeoutPromise(rule.networkTimeoutSeconds ?? 3),
      ]);
      return await cachePut(request, response, rule);
    } catch {
      return await cacheMatch(request, rule) || new Response('Offline', { status: 503 });
    }
  }
  const cached = await cacheMatch(request, rule);
  const revalidate = fetch(request).then((response) => cachePut(request, response, rule));
  if (cached) {
    event.waitUntil(revalidate.catch(() => undefined));
    return cached;
  }
  return revalidate;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (request.mode === 'navigate' && navigationAllowed(url)) {
    event.respondWith(handleNavigation(request));
    return;
  }
  if (PRECACHE_URLS.has(url.href)) {
    event.respondWith(caches.open(HF.precacheName).then(async (cache) =>
      await cache.match(request, { ignoreSearch: false }) || fetch(request)));
    return;
  }
  const rule = ruleFor(request);
  if (rule) event.respondWith(handleRuntime(request, rule, event));
});

self.addEventListener('message', (event) => {
  const message = event.data || {};
  if (message.type === 'HF_SKIP_WAITING') {
    event.waitUntil(self.skipWaiting());
  } else if (message.type === 'HF_GET_VERSION') {
    event.ports[0]?.postMessage({ type: 'HF_VERSION', buildId: HF.buildId });
  } else if (message.type === 'HF_PURGE_RUNTIME' && typeof message.cacheName === 'string') {
    const allowed = HF.runtimeCaching.some((rule) => rule.cacheName === message.cacheName);
    if (allowed) event.waitUntil(caches.delete(HF.runtimePrefix + message.cacheName));
  } else if (message.type === 'HF_SET_BADGE' && 'setAppBadge' in self.navigator) {
    event.waitUntil(message.count > 0
      ? self.navigator.setAppBadge(message.count)
      : self.navigator.clearAppBadge());
  }
});

function notificationRouteAllowed(route) {
  try {
    const url = new URL(route || HF.documentFallback, self.location.origin);
    if (url.origin !== self.location.origin || !pathWithinScope(url.pathname)) return false;
    const allowlist = HF.notifications?.routeAllowlist ?? [];
    return allowlist.length === 0 || allowlist.some((prefix) => url.pathname.startsWith(prefix));
  } catch {
    return false;
  }
}

function notificationAsset(value, fallback) {
  try {
    const candidate = typeof value === 'string' && value.length <= 2048 ? value : fallback;
    if (typeof candidate !== 'string' || candidate.length > 2048) return undefined;
    const url = new URL(candidate, self.location.origin);
    return url.origin === self.location.origin && pathWithinScope(url.pathname) ? url.href : undefined;
  } catch {
    return undefined;
  }
}

if (HF.notifications) {
  self.addEventListener('push', (event) => {
    event.waitUntil((async () => {
      let data = {};
      try { data = event.data?.json() ?? {}; } catch { data = { body: event.data?.text() }; }
      const title = String(data.title || HF.notifications.defaultTitle || 'Notification').slice(0, 120);
      const body = String(data.body || HF.notifications.defaultBody || '').slice(0, 500);
      const route = notificationRouteAllowed(data.route) ? data.route : HF.documentFallback;
      const options = {
        body,
        icon: notificationAsset(data.icon, HF.notifications.defaultIcon),
        badge: notificationAsset(data.badge, HF.notifications.defaultBadge),
        tag: typeof data.tag === 'string' ? data.tag.slice(0, 120) : undefined,
        renotify: Boolean(data.renotify),
        data: { route, payloadVersion: Number(data.version || 1) },
      };
      if (Number.isFinite(data.badgeCount) && 'setAppBadge' in self.navigator) {
        await self.navigator.setAppBadge(Math.max(0, data.badgeCount));
      }
      await self.registration.showNotification(title, options);
    })());
  });

  self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil((async () => {
      const route = notificationRouteAllowed(event.notification.data?.route)
        ? event.notification.data.route
        : HF.documentFallback;
      const target = new URL(route, self.location.origin).href;
      const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      const sameOrigin = clients.filter((item) => new URL(item.url).origin === self.location.origin);
      const client = sameOrigin.find((item) => item.visibilityState === 'visible') || sameOrigin[0];
      if (client) {
        await client.focus();
        client.postMessage({ type: 'HF_NOTIFICATION_ROUTE', route });
      } else {
        await self.clients.openWindow(target);
      }
    })());
  });

  self.addEventListener('notificationclose', (event) => {
    event.waitUntil(postToClients({
      type: 'HF_NOTIFICATION_CLOSE',
      tag: event.notification.tag || null,
    }));
  });

  self.addEventListener('pushsubscriptionchange', (event) => {
    event.waitUntil(postToClients({ type: 'HF_PUSH_SUBSCRIPTION_CHANGE' }));
  });
}
`;
}
